### ISSUE TITLE
Move ingest pipeline to Snakemake workflow and include alignment

### ISSUE THREAD

**Issue by trvrb** [nextstrain/ncov-ingest#111]
Currently the `ncov-ingest` pipeline is a collection of GitHub Actions that run on GitHub's servers. We'd have more control over these and the ability to do heavier weight computation (like alignment) if we move to a generic Snakemake workflow that can be run on AWS (via `nextstrain build --aws-batch`) or on a cluster.

At this point, alignment is uploaded from `ncov` pipeline here: https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/export_for_nextstrain.smk#L283. However, it would make sense for provisioning entrypoint files like `metadata.tsv`, `sequences.fasta` and `aligned.fasta` via `ncov-ingest` to have a clean separation between these two repos.

**Comment by tsibley** [comment]
An update: As of today, ingests now run on AWS (https://github.com/nextstrain/ncov-ingest/pull/120). The migration to Snakemake was started by Richard with https://github.com/nextstrain/ncov-ingest/pull/118 but is still a draft/incomplete.

**Comment by huddlej** [comment]
This issue was resolved by https://github.com/nextstrain/ncov-ingest/pull/231
