### ISSUE TITLE
Add GISAID accessions to the GenBank metadata file

### ISSUE THREAD

**Issue by tsibley** [nextstrain/ncov-ingest#125]
The GISAID metadata references GenBank accessions, but the GenBank metadata doesn't have any GISAID accessions. Refactor how these accessions are tracked and cross-referenced in `transform-gisaid` and `transform-genbank` so they share a _source-data/_ file separate from annotations.

See also https://github.com/nextstrain/ncov-ingest/pull/124#issuecomment-772940020 re: versioned vs. non-versioned GenBank accessions.

**Comment by tsibley** [comment]
@AngieHinrichs I'm going to lift over your wonderful annotations to our GenBank metadata too so it can point back to GISAID. There will be some upcoming code/data changes for that in this repo, which may impact your update process? I wanted to flag this for you now so you're aware. Happy to discuss, and I can flag again when there's code to show.

**Comment by AngieHinrichs** [comment]
@tsibley delighted to hear that you're working on the GenBank metadata side!  I have my own [cobbled-together flow](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/getNcbi.sh) to integrate NCBI Virus API download files with a couple BioSample attributes from eutils, and locally computed Nextclade and Pangolin, but I'll bet ncov-ingest results will be better!  :)  Are the GenBank metadata results going to be available for public download?  I would like to take a look & compare notes.  Thanks!

And no worries about my update process, I imagine it will be no trouble to swizzle columns to whatever new form is required.  :)

**Comment by tsibley** [comment]
@AngieHinrichs

> but I'll bet ncov-ingest results will be better! :)

Well, we'll see! Right now it's not getting as much usage, but we do want to improve it.

> Are the GenBank metadata results going to be available for public download?

Yes! You can take a peek at the current outputs here:

* https://data.nextstrain.org/ncov-ingest/genbank.ndjson.gz
* https://data.nextstrain.org/ncov-ingest/genbank_metadata.tsv.gz
* https://data.nextstrain.org/ncov-ingest/genbank_sequences.fasta.gz

but these specific URLs will soon vanish when we move the files around before documenting/distributing more widely. So please don't rely on these quite yet.

> And no worries about my update process, I imagine it will be no trouble to swizzle columns to whatever new form is required. :)

:grin:

**Comment by tsibley** [comment]
@AngieHinrichs Once [this PR](https://github.com/nextstrain/ncov-ingest/pull/127) is merged, ncov-ingest will be using an `accessions.tsv` file that's currently just two columns and shared between the GISAID and GenBank ingestion pipelines. For an example, see the [copy in the PR](https://github.com/nextstrain/ncov-ingest/blob/573d7664f11b0e20c661821fe74b5e75de032bca/source-data/accessions.tsv).

**Comment by AngieHinrichs** [comment]
Those files look great!  So from 573d7664 it looks like in the future, I can simply add mappings to source-data/accessions.tsv instead of source-data/gisaid_annotations.tsv?

Any plans to add Nextclade and pangolin assignments?

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs Once [this PR](https://github.com/nextstrain/ncov-ingest/pull/127) is merged, ncov-ingest will be using an `accessions.tsv` file that's currently just two columns and shared between the GISAID and GenBank ingestion pipelines. For an example, see the [copy in the PR](https://github.com/nextstrain/ncov-ingest/blob/573d7664f11b0e20c661821fe74b5e75de032bca/source-data/accessions.tsv).

Oops, crossed in the ether.  Perfect!

**Comment by tsibley** [comment]
> Any plans to add Nextclade and pangolin assignments?

No timeline at the moment, but I 100% expect we'll add them as we start using the GenBank dataset more.
