### ISSUE TITLE
Know how for external users with GISAID accounts

### ISSUE THREAD

**Issue by michalkowalski94** [nextstrain/ncov-ingest#148]
Hi,
It would be great if there were any docs, know how's or tutorials on how to use ncov-ingest by external users.
Could You provide such thing or contact me via e-mail?

**Comment by michalkowalski94** [comment]
Hi,
I would really appreciate fast response

**Comment by emmahodcroft** [comment]
Hi @michalkowalski94 Thanks for reaching out and I'm sorry you haven't heard back sooner. Unfortunately at the moment I don't think we have very comprehensive documentation or tutorials on how to use `ncov-ingest`. It's mostly maintained by the Nextstrain 'build shepherds' who use it to prepare data from GISAID for the weekday Nextstrain SARS-CoV-2 runs, which are run through the `ncov` repository. 

While I agree it would be fantastic to provide more documentation for how to use `ncov-ingest`, I'm afraid I don't know if we will be able to provide this quickly, as all of us are pretty pressed for time with the pandemic. 

What I can say which might be helpful is that the pipeline takes as input a file provided by GISAID (this needs to be applied for via GISAID) , and this is then processed through a [series of scripts](https://github.com/nextstrain/ncov-ingest/blob/master/bin/ingest-gisaid) to produce a metadata and sequences alignment file (`nextmeta` and `nextfasta` which are available to some users on GISIAID under 'downloads').

I'm sorry there isn't more help available right now!

**Comment by rneher** [comment]
this repo is mostly useful for process the `ndjson` file provided by gisaid. Unless you are dealing with this ndjson, you should be better off using the output of this workflow that is available for download in gisaid.
