### ISSUE TITLE
What can be used as GISAID_API_ENDPOINT?

### ISSUE THREAD

**Issue by yunfeiguo** [nextstrain/ncov-ingest#158]
Hi there, could you clarify a bit on what can be used as GISAID_API_ENDPOINT? Is it something special the GISAID shared with Nextstrain? Thanks.

**Comment by trvrb** [comment]
Hi @yunfeiguo. Nextstrain has been provisioned with a specific GISAID API endpoint and specific credentials for this endpoint. Other web apps listed at https://www.gisaid.org/collaborations/enabled-by-hcov-19-data-from-gisaid/ have been provisioned with their own API endpoints. API access is separate from basic user access granted by completing GISAID registration at https://www.gisaid.org/registration/register/. You would need to contact GISAID directly about API access. Hope this helps and best of luck with your research.

**Comment by yunfeiguo** [comment]
Thanks, that was helpful!
