### ISSUE TITLE
Use NCBI Datasets command line tool to download SARS-CoV-2 data from GenBank

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#184]
Start using the [NCBI Datasets command line tool](https://www.ncbi.nlm.nih.gov/datasets/docs/quickstarts/command-line-tools/) to download SARS-CoV-2 data from GenBank. This would replace the current [fetch-from-genbank script](https://github.com/nextstrain/ncov-ingest/blob/master/bin/fetch-from-genbank), which has been consistently failing over the last few weeks. 

I think we would mostly be interested in the [virus metadata report](https://www.ncbi.nlm.nih.gov/datasets/docs/data-packages/sars-cov-2-genome/#virus-data-report) and the [genomic FASTA](https://www.ncbi.nlm.nih.gov/datasets/docs/data-packages/sars-cov-2-genome/#genomic-fasta). 

This will also require some updates to the [transform-genbank script](https://github.com/nextstrain/ncov-ingest/blob/master/bin/transform-genbank) since the metadata and sequences will be in separate files instead of one NDJSON.

**Comment by rneher** [comment]
Would using the REST-API be a substitute here?

https://www.ncbi.nlm.nih.gov/datasets/docs/reference-docs/rest-api/#get-/virus/taxon/-taxon-/genome/download

We would need to apply for an API key. but the data they provide looks pretty clean.

**Comment by rajivshah3** [comment]
Hi @joverlee521 , would I be able to work on this issue? I wonder if it would be better to use the CLI or their Python package (both mentioned at https://www.ncbi.nlm.nih.gov/datasets/docs/v1/how-tos/virus/get-sars2-genomes/#download-by-taxon)

**Comment by chaoran-chen** [comment]
@rajivshah3, that's an interesting resource. I hope that you can actually get the full dataset with the CLI/python package; through [this website](https://www.ncbi.nlm.nih.gov/datasets/coronavirus/genomes/), it's only possible to get <1.5 million of the 5 million sequences - very strange?

I don't know how you do it right now but if you have struggle to get the lab information, you could try out this link: https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&save=file&log$=seqview&db=nuccore&report=xml&id=ON692539&conwithfeat=on&hide-cdd=on

That file includes the full author names and the affiliations. It also includes information about the sequencing technology and assembly technique which I think are very useful as well. I'd love to get those data for LAPIS :) I've heard people asking about statistics on used sequencing platforms - with LAPIS, it would be easy to get those.

**Comment by joverlee521** [comment]
Hi @rajivshah3, thank you for offering to work on this! 

From what I remember the last time I looked into NCBI Datasets, it lacks the list of authors that we get from NCBI Virus. NCBI Datasets is still in Beta, so they may add this field eventually, but we would not want to use the tool until it has the authors field. This field is essential for us give credit to the original authors of the genomes.

**Comment by joverlee521** [comment]
FYI, I'm digging into this again since NCBI Datasets now includes [submitter info](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-reports/virus/#ncbi-datasets-v2-reports-VirusAssembly-SubmitterInfo) in their virus report.

Our GenBank ingest has been taking anywhere from 9 - 24 hours due to the slow download from NCBI Virus. I think switching to NCBI Datasets will speed things up significantly.

**Comment by emmahodcroft** [comment]
Thanks for picking this up again Jover!
