### ISSUE TITLE
Allow data from outside GISAID

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/ncov-ingest#19]
We're often getting genomes + metadata shared prior to GISAID release. It would be good to allow this to be incorporated into this repo for consumption by the ncov pipeline. Not sure of the best way to address this -- we could commit a "non-GISAID" FASTA + TSV, but that may cause the repo to grow too big over time.

**Comment by kairstenfay** [comment]
@joverlee521 and @tsibley are currently working on importing data from GenBank which may close this issue.

**Comment by kairstenfay** [comment]
Closing this issue since we've now split our workflow to process data from GISAID or Genbank. The refactoring done in #55 should allow other, external sources of data to be ingested as well.
