### ISSUE TITLE
Only trigger preprocess if ingest if there are new sequences or new annotations

### ISSUE THREAD

**Issue by trvrb** [nextstrain/ncov-ingest#235]
**Context**  
From watching behavior of `GISAID fetch and ingest` action and from reading through the script `ingest-gisaid`: https://github.com/nextstrain/ncov-ingest/blob/master/bin/ingest-gisaid#L166, I'm pretty sure that preprocess is always triggered.

This means that we can't have `ingest-gisaid` running every ~6 hours to better catch updates to the endpoint by GISAID. (Unless we want a whole lot of wasted processing, and even then it's going to overwrite manual updates)

**Description**   
Running `ingest-gisaid` should compare `metadata.tsv.gz` produced during the script's run to the file `metadata.tsv.gz` on S3, along with a similar comparison of `sequences.fasta.xz`. Only if hashes of either metadata or sequences are different should preprocess be triggered.

cc @tsibley @joverlee521

**Comment by joverlee521** [comment]
Should we push this diff even further upstream and only run `ingest` when there's new/updated GISAID data? 

For `ingest-gisaid --fetch`, we can diff the `gisaid.ndjson` against the `gisaid.ndjson.xz` on S3 and only run `ingest` + `preprocess` if there are updates.

**Comment by huddlej** [comment]
Is it fair to say this issue has been resolved by https://github.com/nextstrain/ncov-ingest/pull/237 speeding up the ingest workflow? Or is this still an issue we need to resolve by as described above?

**Comment by tsibley** [comment]
@huddlej I think that's fair, esp. given this comment from @trvrb [on Slack](https://bedfordlab.slack.com/archives/CTZKJC7PZ/p1652917382673139):

> I think rerunning phylogenetics workflow is not too big of a deal. Especially as we expect to continue to make refinements to ncov that would be good to be live (like https://github.com/nextstrain/ncov/commit/662ce24345454170cc914d8d872bdeff94752f8a).

Plus, it seems like things have been ~fine without this for the past ~6 months.
