### ISSUE TITLE
Profile ncov-ingest

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#240]
Currently, GISAID ingest takes ~4 hours. We should profile the pipeline to figure out if improvements can be made without a major overhaul (i.e. incremental ingest with caches or a database). 

- Once the pipeline has been converted to Snakemake via #231, we can use Snakemake's `benchmark`, `--stats`, and/or `--report` to get an overview of the pipeline. We should upload the outputs to S3 to have a record of changes over time. 
- @tsibley suggested using Python profilers such as [py-spy](https://github.com/benfred/py-spy) to inspect specific scripts that are pain points in the pipeline.

**Comment by jameshadfield** [comment]
Another aspect of profiling is the removal / storage of (large) files. This is applicable both for storage space while running, as well as the behavior of `nextstrain build --aws-batch` which will zip and upload the current working directory to one of our S3 buckets. 

As of 45dcea6b8deb516d03abecf7e6d8a305ebf4a8b5, currently we use snakemake's `temp()` and the `./bin/clean script (which is controlled by a config argument).

**Comment by jameshadfield** [comment]
PR #231 has been merged and I've just started a run with [this GitHub action](https://github.com/nextstrain/ncov-ingest/actions/runs/1528078822).

**Comment by joverlee521** [comment]
Using `--report` is dependent on https://github.com/nextstrain/docker-base/pull/219
