### ISSUE TITLE
Store line count in object metadata to avoid network transfer just to count lines

### ISSUE THREAD

**Issue by tsibley** [nextstrain/ncov-ingest#243]
`notify-on-record-change` compares counts lines in a local file and remote file. It counts lines in the remote file by downloading and decompressing it in its entirety.

https://github.com/nextstrain/ncov-ingest/blob/94081fdcc0d54f01d4a10ef7a53197b4f6296dd8/bin/notify-on-record-change#L16-L18

This presumably takes some non-trivial amount of network transfer time! Instead of doing that unnecessary work, we could store line counts in the object metadata, like we already do for `sha256sum`, and then very quickly be able to get a remote file line count.

**Comment by rajivshah3** [comment]
Hi @tsibley , do you think #313 will work for this?

**Comment by tsibley** [comment]
@rajivshah3 Commented over there. Thanks for flagging!

**Comment by joverlee521** [comment]
Closed by #316
