### ISSUE TITLE
Remove "REDUNDANT ANNOTATED METADATA" messages from technical logs

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/ncov-ingest#250]
```
[batch] REDUNDANT ANNOTATED METADATA : LR757995 division Hubei
[batch] REDUNDANT ANNOTATED METADATA : LR757995 location Wuhan
[batch] REDUNDANT ANNOTATED METADATA : LR824035 country Switzerland
[batch] REDUNDANT ANNOTATED METADATA : LR824035 region Europe
[batch] REDUNDANT ANNOTATED METADATA : MZ918713.1 gisaid_epi_isl EPI_ISL_2423684
```

It seems that this is domain-specific info that should be read by ingest build shepherds. But right now these messages only clog the logs on Github Actions and AWS Batch making diagnostics harder.

Attached is 9 megs (!) of these messages from genbank ingest logs.

I propose we remove those or redirect them to a file, where shepherds can find them.

Thread on Slack: https://bedfordlab.slack.com/archives/CTZKJC7PZ/p1639149188358600

Attachments:
[REDUNDANT ANNOTATED METADATA.txt](https://github.com/nextstrain/ncov-ingest/files/7693706/REDUNDANT.ANNOTATED.METADATA.txt)

**Comment by emmahodcroft** [comment]
Agree with Ivan - let's pipe this to a file that can be used by build shepherds - perhaps the GISAID one can go to Slack. The Genbank one maybe not, as it's so huge. (But having two different actions may be more difficult than it's worth)
