### ISSUE TITLE
Run ncov-ingest on Terra

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov-ingest#289]
## Description

Allow users with GISAID API endpoint access to run ncov-ingest with their credentials on Terra.

## Possible solutions

Create a separate task in the ncov WDL workflow that downloads and runs the ingest workflow.

**Comment by j23414** [comment]
Done and working
* ncov ingest code: https://github.com/nextstrain/ncov/blob/wdl/temp_ingest/workflow/wdl/tasks/ncov_ingest.wdl#L3
* Import into Terra via Dockstore: https://dockstore.org/workflows/github.com/nextstrain/ncov:wdl/temp_ingest?tab=info
* User Guide: https://github.com/nextstrain/ncov/blob/wdl/temp_ingest/docs/src/guides/run-ingest-on-terra.rst
* Whole Workflow Diagram: https://raw.githubusercontent.com/j23414/wdl_pathogen_build/main/data/Terra.png
