### ISSUE TITLE
Phase out `run-nextclade` script

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#327]
From @ivan-aksamentov in review of #320:

> Sometimes later we could also phase-out the `run-nextclade` script, because it does not do much, and we could call Nextclade binary directly. Although a separate step of downloading the dataset will be necessary.

**Comment by fanninpm** [comment]
> Although a separate step of downloading the dataset will be necessary.

As I mentioned in https://github.com/nextstrain/ncov-ingest/pull/320#issuecomment-1199809555, Nextclade v2.4.0 allows downloading a dataset at the same time as `nextclade run`.

**Comment by joverlee521** [comment]
Resolved by https://github.com/nextstrain/ncov-ingest/pull/372
