### ISSUE TITLE
Alert for 'Future Dates' When Pre-Processing (Ingesting)

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov-ingest#33]
**Context**  
Currently full runs take 2 hours. If sequences aren't checked when they come in (by scrolling through the incredibly helpful messages that appear in Slack) then it's very easy to miss if dates are seriously incorrect - being from the *future*. 

However, these dates mess up the whole run, as they ruin the tree, and the only fix is to add to `exclude.txt` and re-run. It only takes missing a couple to waste half a day on runs! 

Often we can get quick feedback from submitters on the correct date (or, they can be corrected online), so we wouldn't necessarily want these auto-kicked out (I think?), but it would be great to be alerted to these at the same time as we are alerted to new sequences, so we can immediately add to `exclude.txt` and reach out to submitters.

**Description**   
When sequence come in, can they be checked against today's date. If they are > today's date ('from the future'), then can we get a big alert on Slack, giving a list of the 'futuristic sequences' so that we know immediately. Then we are able to take action!

**Examples**  & **Possible solution**   

I think a message like the ones we currently get would be great. Maybe another Icon so that they are really easy to spot - if a lot comes through sometimes the messages are easy to miss!

**Comment by tsibley** [comment]
> Often we can get quick feedback from submitters on the correct date (or, they can be corrected online), so we wouldn't necessarily want these auto-kicked out (I think?), but it would be great to be alerted to these at the same time as we are alerted to new sequences, so we can immediately add to `exclude.txt` and reach out to submitters.

If ncov-ingest doesn't drop the sequences on a known bad date, then the build it starts is destined to be bad, which I think just makes more work for humans and computers alike. Someone either has to go cancel the known-to-be-bad build or remember to ignore it later when it completes. And if manually added to excludes.txt, then someone has to remember to remove it later.

If the sequences with bad dates _are_ dropped, then the build can still be used if desired. The alert will help folks track down corrections and update annotations, which will then launch a new build automatically. If the date is corrected externally, then the sequence stops being dropped automatically and no one has to go remove anything from exclude.txt.

I'm thinking that this pipeline could even generate a list of automatically excluded sequences, commented with the reason for each, and that file could then be used by the build in conjunction with the manually-curated exclude.txt.

**Comment by emmahodcroft** [comment]
Yes, you make good points Tom.  I think a list of automatically excluded sequences for bad dates would be particularly really useful. A lot of the reasons for excluding we might not be able to do much about - but this is actually something we often get fast responses on - because people realise how silly it is, I guess! So the contacts are 100% worth the time (can't say that all the time!). 

So, yes, I think I'm brought around to the idea for auto-dropping these - but please can we get a list (to slack if at all possible, to avoid forgetting to check!) of what's been dropped due to bad date in particular (even if followed by those dropped for other reasons) so we can be sure to chase up submitters about it? That would be awesome!

**Comment by tsibley** [comment]
Yep, we could do a diff of the previous vs. new excluded seqs (with the explanatory comments) and alert that into Slack.

**Comment by kairstenfay** [comment]
@tsibley Were you imagining that we would maintain a TSV of excluded rows? Or creating a new file for automated exclusions in the style of the existing `exclusions.txt`? I can see us adding a new column that describes why a row was dropped. Or did you have something else in mind? I'm working on incorporating this feedback into #43.

**Comment by kairstenfay** [comment]
@emmahodcroft please see @Jover's [comment from #47](https://github.com/nextstrain/ncov-ingest/pull/43#pullrequestreview-425669537)

> General comment: it's nice to have the notifications for the future dates, but I wonder if it's necessary to generate an additional exclude.txt file. Can we not use the augur filter --max-date option to automatically filter out future dates in the ncov build?

**Comment by kairstenfay** [comment]
The alerting is resolved via #43, but the actual filtering is soon-to-be-merged at nextstrain/ncov/pull/401

**Comment by kairstenfay** [comment]
Closed via #43 and nextstrain/ncov/pull/401
