### ISSUE TITLE
Pull data from "SARS-CoV-2 Sequence Data from Germany"

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#331]
### Context
Similar to #329, there has been a significant drop off in sequences from Germany in the NCBI data since ~April 2022 (this issue was originally raised by @corneliusroemer in [Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1659103066027229)):

![Screen Shot 2022-07-29 at 10 40 29 AM](https://user-images.githubusercontent.com/40774762/181815076-2a895d74-aa69-4a70-84b7-51d249bca833.png)

### Description
We can update the open pipeline to pull metadata and sequences directly from the ["SARS-CoV-2 Sequence Data from Germany" GitHub repo](https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland).

### Possible solution
[Similar solutions](https://github.com/nextstrain/ncov-ingest/issues/329#issuecomment-1195886889) from #329 will apply here.

**Comment by joverlee521** [comment]
I think the solution for directly pulling RKI sequences will be similar to [my ideas for the COG-UK data](https://github.com/nextstrain/ncov-ingest/issues/329#issuecomment-1266155720).

The different step here might be how to remove the RKI sequences from the GenBank data. I have not found an accession linkage file for the RKI data. However, we can do a blanket removal of all sequences linked to the [RKI BioProject](https://www.ncbi.nlm.nih.gov/bioproject/PRJEB44987).

**Comment by corneliusroemer** [comment]
We could simply remove all German sequences uploaded to Genbank from March 2022 onwards and only spike from Germany's repo from that date onwards as a quick fix.
This would be 80/20, more effort may not be worth it.

**Comment by joverlee521** [comment]
Resolved by #365
