### ISSUE TITLE
Add genbank_accession_rev field

### ISSUE THREAD

**Issue by chaoran-chen** [nextstrain/ncov-ingest#359]
### Context
For the "open" instance of LAPIS, we use data from https://data.nextstrain.org/files/ncov/open/. It would be very useful if users can know which version of the sequences they are getting from LAPIS but unfortunately, the `genbank_accession` field in the metadata.tsv file only contains the accession without the version number suffix (e.g., `OV377246`).

The mpox data already contains a field with the version number.

### Description
It would be great to have an additional column (`genbank_accession_rev`?) that contains the version number as well (e.g., `OV377246.1`).

(cc @cecivale)

**Comment by j23414** [comment]
Looks like we're pulling "genbank_accession_rev" here:

* https://github.com/nextstrain/ncov-ingest/blob/master/bin/genbank-url#L49

But somehow it's not being passed onward to the metadata. For Dengue, I had to add it to the list of output columns like

* https://github.com/nextstrain/dengue/blob/new_ingest/ingest/config/config.yaml#L54

But in **ncov-ingest** I think we'd have to add it to:

* https://github.com/nextstrain/ncov-ingest/blob/master/lib/utils/transform.py#L8

@joverlee521 does that look right?
