### ISSUE TITLE
Publish gene translation files

### ISSUE THREAD

**Issue by chaoran-chen** [nextstrain/ncov-ingest#394]
Hi. May I bother you with another request? Would it be possible for you to also publish the gene translation fasta files for the open data?

(We need these files for LAPIS. At the moment, we import most of the data including nextclade.tsv directly from the downloaded files but then still run nextalign ourselves on all sequences just to obtain the AA sequences.)

**Comment by corneliusroemer** [comment]
Yes of course, I'll have a look. This shouldn't be too difficult.

By the way, the nextclade.tsv now contains timestamp of dataset, as well as version of nextclade and time of run.

**Comment by chaoran-chen** [comment]
Hi @corneliusroemer, I just would like to remind you of this issue. LAPIS v2 is coming closer and it would be amazing if we can avoid any data preprocessing for the open instance and just use the downloaded data from Nexttrain.

**Comment by chaoran-chen** [comment]
Hi @corneliusroemer, LAPIS v2 is now very close and we have started setting up the test server (https://github.com/GenSpectrum/LAPIS/issues/124). It would be really amazing if we can download the translated sequences directly so that we don't have to set up the whole preprocessing pipeline again (with caching, etc.) and redo all the work. Do you think that it would be possible to implement this issue within the next two weeks?

**Comment by chaoran-chen** [comment]
@corneliusroemer, do I understand correctly that after the next run, the translations will be available at https://data.nextstrain.org/files/ncov/open/translation_E.fasta.zst?

**Comment by corneliusroemer** [comment]
@chaoran-chen Yes, that's right. Translations should be there in <24hr
