### ISSUE TITLE
Metadata includes Nextstrain clades in the `Nextclade_pango` column

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#456]
## TODOs

- [x] verify GISAID metadata output
- [x] verify open metadata output

## Context

Determined as the root cause for https://github.com/nextstrain/forecasts-ncov/issues/104

Both the private GISAID and public open metadata include Nextstrain clades (e.g. `24A (JN.1)`) in the `Nextclade_pango` column. 

The timing of the downstream errors coincides with the [latest release of Nextclade datasets](https://github.com/nextstrain/nextclade_data/releases/tag/2024-07-03--08-29-55Z) and the [latest release of Nextclade v3.8.0](https://github.com/nextstrain/nextclade/releases/tag/3.8.0)

**Comment by joverlee521** [comment]
The workflow [blinding appends Nextclade TSV outputs](https://github.com/nextstrain/ncov-ingest/blob/f5f238be75314570b9a7050886b59cad128737bb/workflow/snakemake_rules/nextclade.smk#L244-L274). I'm assuming something changed in the outputs between Nextclade versions, leading to this error. (Will dig into this later...)

I'm going to cancel the currently running ncov-ingest jobs, upload the `*.renew` files to trigger a full Nextclade run, and re-run the ingest jobs.

**Comment by joverlee521** [comment]
Uploaded *.renew files

```
$ aws s3 cp - s3://nextstrain-ncov-private/nextclade.tsv.zst.renew < /dev/null
$ aws s3 cp - s3://nextstrain-data/files/ncov/open/nextclade.tsv.zst.renew < /dev/null
$ aws s3 cp - s3://nextstrain-ncov-private/nextclade_21L.tsv.zst.renew < /dev/null
$ aws s3 cp - s3://nextstrain-data/files/ncov/open/nextclade_21L.tsv.zst.renew < /dev/null
```

Running [GISAID](https://github.com/nextstrain/ncov-ingest/actions/runs/9845519969) and [open](https://github.com/nextstrain/ncov-ingest/actions/runs/9845518594) workflows.

**Comment by joverlee521** [comment]
Ah right, open workflow is blocked on https://github.com/nextstrain/ncov-ingest/issues/455. Oh how all stars aligned this weekend 😅 

At least we'll resolve the issue in GISAID metadata for now.

**Comment by joverlee521** [comment]
>  I'm assuming something changed in the outputs between Nextclade versions, leading to this error. (Will dig into this later...)

Nextclade 3.8.0 added new columns for the new relative mutations feature *and* changed the order of existing output columns:

|order|nextclade\-3\.7\_columns\_name|nextclade\-3\.8\_columns\_name                      |
|---:|--------------------|----------------------------------------------------|
|1   |index               |index                                               |
|2   |seqName             |seqName                                             |
|3   |clade               |clade                                               |
|4   |Nextclade\_pango    |clade\_display                                      |
|5   |partiallyAliased    |clade\_who                                          |
|6   |clade\_nextstrain   |clade\_nextstrain                                   |
|7   |clade\_who          |partiallyAliased                                    |
|8   |clade\_display      |Nextclade\_pango                                    |

The change in ordering is the root cause of this issue, but the new columns would have messed things up too. 

Maybe to guard against this, we should at least have a check that the new Nextclade outputs columns match the columns of the Nextclade cache.

**Comment by corneliusroemer** [comment]
Oh no, I always did renew whenever I updated Nextclade datasets, but the software version wasn't on my radar.

Thanks for tracking this down!

**Comment by corneliusroemer** [comment]
> Also I need to be more careful when releasing stuff :)

I don't think this is at all on you @ivan-aksamentov - TSV columns can change, we shouldn't rely on stability and invalidate cache properly.

**Comment by joverlee521** [comment]
Oy, the [GISAID ingest](https://github.com/nextstrain/ncov-ingest/actions/runs/9845519969) is still running after 20+ hours...if it runs past 24 hours, the GH Action workflow will show success/complete, but the job will continue to run on AWS Batch.  

(I will add final stats.json to https://github.com/nextstrain/ncov-ingest/issues/446)

**Comment by corneliusroemer** [comment]
Ah yeah - we almost never run with the 21L touchfiles, so it's quite some extra work to do. Choosing a larger machine in the future might work if we know there's a pending full rerun. Nextclade parallelizes very well, so can go to a machine with say 64 cores or even larger.

**Comment by corneliusroemer** [comment]
> Oh, I'm not sure the workflow is utilizing this because there are no threads defined for the Snakemake rule.

No need for threads, nextclade uses all by default. What I meant to say was that we can use more cores to speed things up if we find workflows take too long. See comment over at #459 :)

**Comment by joverlee521** [comment]
Verified the full reruns of Nextclade fixed the metadata for both GISAID and open.
