### ISSUE TITLE
Ignore Nextclade cache on new Nextclade version or dataset version

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#457]
We've had a history of caching issues (https://github.com/nextstrain/ncov-ingest/issues/456, https://github.com/nextstrain/ncov-ingest/issues/392) come up whenever there's a new release of Nextclade or SARS-CoV-2 Nextclade dataset and we forget to manually upload the `*.renew` files to trigger the full re-run.

The workflow should automatically ignore the Nextclade cache if it encounters a new Nextclade version or dataset version.

**Comment by joverlee521** [comment]
Also prompted by discussion in [blab/forecasting project](https://docs.google.com/document/d/1uioKPOF1U34EiheboX6UVe6pCnfRkdZouUXjgQLLLa4/edit#heading=h.b6uq0bfygq0t) to surface Nextclade/dataset version in the [sequence counts generated by forecasts-ncov/ingest](https://github.com/nextstrain/forecasts-ncov/tree/main/ingest#sequence-counts)

**Comment by corneliusroemer** [comment]
Good idea, yes.

Shouldn't be hard to set renew files programmatically based on equality or not of the columns in the existing files with the current software and dataset version!
