### ISSUE TITLE
Define threads for Nextclade rules

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#459]
Prompted by https://github.com/nextstrain/ncov-ingest/issues/456#issuecomment-2218083580

From my reading of [Snakemake docs on threads](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#threads):

> Also, setting a threads: maximum is required to achieve parallelism in tools that (often implicitly and without the user knowing) rely on an environment variable for the maximum of cores to use. 

Makes me think we _need_ to define threads of the Nextclade Snakemake rules in order for Nextclade to parallelize. 

Proposing that we split the workflow cores between the two Nextclade rules:

```diff
diff --git a/workflow/snakemake_rules/nextclade.smk b/workflow/snakemake_rules/nextclade.smk
index 8d24c23..e97c8aa 100644
--- a/workflow/snakemake_rules/nextclade.smk
+++ b/workflow/snakemake_rules/nextclade.smk
@@ -193,6 +193,8 @@ rule run_wuhan_nextclade:
             temp(f"data/{database}/nextclade.translation_{gene}.upd.fasta")
             for gene in GENE_LIST
         ],
+    threads:
+        workflow.cores * 0.5
     benchmark:
         f"benchmarks/run_wuhan_nextclade_{database}.txt"
     shell:
@@ -224,6 +226,8 @@ rule run_21L_nextclade:
         sequences=f"data/{database}/nextclade_21L.sequences.fasta",
     output:
         info=f"data/{database}/nextclade_21L_new_raw.tsv",
+    threads:
+        workflow.cores * 0.5
     benchmark:
         f"benchmarks/run_21L_nextclade_{database}.txt"
     shell:
```

**Comment by corneliusroemer** [comment]
Good idea but I don't think we need to set these threads. All they do, in my experience, is _limit_ parallelism.

Have you checked that there's a need for this? I'm pretty sure things have always been running in parallel just fine.

Nextclade uses all cores by default, unless you tell it through `-j` otherwise. It doesn't read env variables AFAIK

**Comment by corneliusroemer** [comment]
I still don't think this is necessary. I've never used nproc and it seems to report something that nextclade doesn't care about - at least on macOS.

See how these three rules run all in parallel, even though one doesn't mention threads at all.

They all run the same time, using as many jobs as there are cores (unless limited by `-j`). So the threads variable has no effect other than _limiting_ parallelness.

Though it does indeed seem to set some env variable that makes `nproc` report a reduced number of cores. But this is not done through cgroups, so probably has no effect on programs that don't look at those env variables.

Snakefile:
```
rule all:
    input:
        a="a.txt",
        c="c.txt",
        d="d.txt",


rule a:
    input:
        "input.fasta",
    output:
        touch("a.txt"),
    shell:
        """
        echo rule a nproc "$(nproc)"
        time nextclade run -d nextstrain/mpox {input} --output-all nextclade_a
        """


rule c:
    input:
        "input.fasta",
    output:
        touch("c.txt"),
    threads: 4
    shell:
        """
        echo rule c nproc "$(nproc)"
        time nextclade run -d nextstrain/mpox {input} --output-all nextclade_c
        """


rule d:
    input:
        "input.fasta",
    output:
        touch("d.txt"),
    threads: 4
    shell:
        """
        echo rule d nproc "$(nproc)"
        time nextclade run -j {threads} -d nextstrain/mpox {input} --output-all nextclade_d
        """
```

Output:

```
$ snakemake --force
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Using shell: /opt/homebrew/bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
a            1
all          1
c            1
d            1
total        4

Select jobs to execute...
Execute 3 jobs...

[Tue Jul  9 20:22:54 2024]
localrule a:
    input: input.fasta
    output: a.txt
    jobid: 1
    reason: Forced execution
    resources: tmpdir=/var/folders/qf/4kkcfypx0gbfb0t9336522_r0000gn/T


[Tue Jul  9 20:22:54 2024]
localrule d:
    input: input.fasta
    output: d.txt
    jobid: 3
    reason: Forced execution
    threads: 4
    resources: tmpdir=/var/folders/qf/4kkcfypx0gbfb0t9336522_r0000gn/T


[Tue Jul  9 20:22:54 2024]
rule a nproc 1
localrule c:
    input: input.fasta
    output: c.txt
    jobid: 2
    reason: Forced execution
    threads: 4
    resources: tmpdir=/var/folders/qf/4kkcfypx0gbfb0t9336522_r0000gn/T

rule d nproc 4
rule c nproc 4

real    0m3.644s
user    0m9.996s
sys     0m0.405s
Touching output file a.txt.
[Tue Jul  9 20:22:58 2024]
Finished job 1.
1 of 4 steps (25%) done

real    0m3.654s
user    0m9.974s
sys     0m0.423s
Touching output file c.txt.
[Tue Jul  9 20:22:58 2024]
Finished job 2.
2 of 4 steps (50%) done

real    0m4.888s
user    0m9.459s
sys     0m0.376s
Touching output file d.txt.
[Tue Jul  9 20:22:59 2024]
Finished job 3.
3 of 4 steps (75%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Jul  9 20:22:59 2024]
localrule all:
    input: a.txt, c.txt, d.txt
    jobid: 0
    reason: Forced execution
    resources: tmpdir=/var/folders/qf/4kkcfypx0gbfb0t9336522_r0000gn/T

[Tue Jul  9 20:22:59 2024]
Finished job 0.
4 of 4 steps (100%) done
Complete log: .snakemake/log/2024-07-09T202254.489461.snakemake.log

```

Note that the _slowest_ is the one that gets 4 threads but limits nextclade jobs via `-j 4`.

This is _slower_ than not defining threads and not passing jobs for nextclade. So the addition of jobs doesn't make anything faster, just adds lines of codes.

**Comment by corneliusroemer** [comment]
I outputted `env` for each rule, and these are the differences:

```
$ diff env_a.txt env_d.txt 
10c10
< NUMEXPR_NUM_THREADS=1
---
> NUMEXPR_NUM_THREADS=4
28c28
< OPENBLAS_NUM_THREADS=1
---
> OPENBLAS_NUM_THREADS=4
40,41c40,41
< VECLIB_MAXIMUM_THREADS=1
< GOTO_NUM_THREADS=1
---
> VECLIB_MAXIMUM_THREADS=4
> GOTO_NUM_THREADS=4
63c63
< OMP_NUM_THREADS=1
---
> OMP_NUM_THREADS=4
69c69
< MKL_NUM_THREADS=1
---
> MKL_NUM_THREADS=4
```

So it looks like nproc reports what one of these variables says, but these variables are ignored by Nextclade and hence `threads` only has the effect of limiting parallelity (as the default is 1, if ommitted)

**Comment by joverlee521** [comment]
Hmm, I'm getting confused. Isn't there two levels of parallelism going on? 

1. Parallel Snakemake rules
2. Parallel Nextclade processes _within_ a Snakemake rule

As you stated, [1] is _limited_ by threads. However I thought [2] relies on Snakemake reserving the number of cores defined by threads for the single rule? Or am I completely misunderstanding how Snakemake works under the hood?

**Comment by j23414** [comment]
At least for dengue, when I upped the build to 10 trees (instead of 5) and ran

```
git clone https://github.com/nextstrain/dengue.git
cd dengue/phylogenetic

envdir ~/nextstrain/env.d/seasonal-flu nextstrain build --aws-batch --aws-batch-cpus 4 --aws-batch-memory 7200 . --jobs 4
```

It'd return

```
**Job FAILED after 0.2 minutes** (exited 1)
```

When I upped `--jobs 10` then it worked fine, which indicated that Snakemake was not allocating threads properly.

**Comment by joverlee521** [comment]
> Or am I completely misunderstanding how Snakemake works under the hood?

Chatted with @tsibley about this in our 1:1 today and I am misunderstanding. Snakemake's threads are just "guidelines" where we use it, so it does need to be passed to `nextclade run -j {threads}` to be respected by Nextclade. Just defining threads is not enough as Nextclade would still oversubscribe. 

I am still curious whether limiting the threads will be faster than letting the two nextclade jobs compete for resources, so I'll update the workflow to pass in threads to Nextclade tomorrow and see how that affects the runtime.

**Comment by joverlee521** [comment]
> I am still curious whether limiting the threads will be faster than letting the two nextclade jobs compete for resources, so I'll update the workflow to pass in threads to Nextclade tomorrow and see how that affects the runtime.

I took a quick look at run times for this week after adding threads. The runtime when using the Nextclade cache is fast enough that there's no noticeable difference. 

However, there is a difference in a full Nextclade run. Comparing just the `run_wuhan_nextclade` job runtimes:

- 2024-07-08's full run _without_ threads ([snakemake_stats.json](https://github.com/user-attachments/files/16286720/snakemake_stats.json)):  8hrs 54mins (32098s)
- 2024-07-17's full run _with_ threads ([snakemake_stats.json](https://github.com/user-attachments/files/16286738/snakemake_stats.json)): 5hrs 16mins (18997s)

**Comment by joverlee521** [comment]
With [plans to ignore cache with new versions](https://github.com/nextstrain/ncov-ingest/issues/457), I think we will do full runs more often and so it makes sense to keep the defined threads.
