### ISSUE TITLE
standardize characters and casing in location information during ingest

### ISSUE THREAD

**Issue by lmoncla** [nextstrain/ncov-ingest#57]
Currently, when new data is ingested, manual adjustments are frequently required for `division` and `location` fields to fix mundane, recurring issues. For example, `division` and `location` fields frequently include an underscore to separate words, rather than a space. Other times, these fields are spelled correctly, but with incorrect casing (all uppercase, rather than titlecase, for example). An example of this is sequences from Valencia, Spain, which almost always ingested with `division Comunitat_Valenciana`. Currently, these require manually adding each strain to `annotations.tsv` to set `division Comumitat Valenciana`. 

A previous example was that we received sequences from the USA, which were ingested as `region NORTH AMERICA`. These had to be manually altered to `region North America`.

It would be amazing if all location fields (`region`, `country`, `division`, and `location`) could be automatically processed to: 
1. replace underscores between words with spaces
2. convert to title case

These 2 checks/fixes would substantially reduce the amount of manual annotation that would need to occur for some batches of sequences in which this is common. This had been reasonably manageable until yesterday, when we received ~ 400 sequences from Spain, most of which required manual underscore removal across multiple fields.

**Comment by kairstenfay** [comment]
@tsibley @joverlee521 FYI Louise recently described this to me as her current highest priority for ncov-ingest dev work

**Comment by kairstenfay** [comment]
In location fields:
- [ ] replace underscores with space
- [ ] Standardize casing in locations to title case
