### ISSUE TITLE
Standardize dates

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/ncov-ingest#69]
**Current Behavior**  
We don't do any date pre-processing or standardization, allowing invalid ISO 8601 dates (like 2020-5-8) to slip through. This was detected by the recent addition of the `flagged_metadata.txt` file where a bunch of invalid dates were flagged for not being less than or equal to the current date. 

**Expected behavior**  
Non-zero-padded or otherwise invalid dates like 2020-5-8 should be standardized to their expected format, e.g. 2020-05-08.

**Comment by joverlee521** [comment]
Ah, I just realized that I added `format_date_columns` to `transform-genbank` but we can also use it in `transform-gisaid`. I'll make the update in a PR.

**Comment by joverlee521** [comment]
While working through this, I realized that `transform-genbank` has been incorrectly inferring dates! `pd.to_datetime` converts strings that are missing month or day to full dates:
`2020` ->`2020-01-01` and `2020-03` -> `2020-03-01`

**Comment by emmahodcroft** [comment]
I think I ran into this once! Seems familiar...
