### ISSUE TITLE
GitHub API soon to deprecate basic authentication

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/ncov-ingest#74]
Yesterday I used the manual `./bin/trigger` script for the first time with the `--user` option and received this automatic email from GitHub:

```
Hi @kairstenfay,

On July 3rd, 2020 at 17:15 (UTC) you used a password to access an endpoint through the GitHub API using curl/7.58.0:

https://api.github.com/repositories/239887733/dispatches

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
```

We may want to consider removing this option from `./bin/trigger` and updating the README.

**Comment by tsibley** [comment]
Yeah, GitHub is strongly pushing early switchovers here even though it'll continue to work until November (albeit with occasional brownouts).
