### ISSUE TITLE
Alert Certain Users to New Sequences from GISAID

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov-ingest#79]
**Context**  
At least two Nextstrain members are currently maintaining more custom builds (Emma maintains USA South-Central/Texas/Louisiana builds, Richard maintains ECDC Europe builds, and both maintain a Swiss build). With decreasing frequency of `ncov` builds, it's become a little harder to notice when new sequences from a country/division/region of interest come in.

It would be cool if there were a way to ping one or more users on Slack about the arrival of new sequences from an area of interest. For example, Emma would find it useful to know whenever we get new sequences from Texas or Louisiana so she can re-run the custom local builds there. Both Emma & Richard would probably find it useful to know when new Swiss sequences appear.

**Description**   
It would be neat if somewhere in 'ingest' it could check against a list of areas of interest and alert the appropriate people when new sequences from these areas pop up. Could be either just tags in a message in #ncov-gisaid-updates channel, or could be private messages - whatever would work easier I guess!
 
Perhaps somewhere in the 'ingest' script there could be a text/JSON/etc file where one can put their slack username and the area they'd like to be alerted to - then any Nextstrain member could easily add or remove alerts as they need/want! For example:

```
username    level     area-name
emmahodcroft    division    Texas
emmahodcroft    division    Louisiana
rneher    country    Switzerland
emmahodcroft    country    Switzerland
...
```

**Comment by emmahodcroft** [comment]
(A note about usernames - I don't know if it applies here, but for Kyber messages I've had to sometimes use a weird version of people's usernames to successfully tag them (ex: `<@moira.zuber>`) - dunno if that would apply here too.)

**Comment by kairstenfay** [comment]
@emmahodcroft do you want notifications for new resolutions and their exposures, too? e.g. if you have an alert for "USA", then you want to be notified on new strains where country = 'USA' or country_exposure = 'USA'?

**Comment by emmahodcroft** [comment]
We don't get quite as much exposure information as we used to, so I imagine it wouldn't make a huge difference, but I'd say it would be interesting to know both, if possible!

**Comment by kairstenfay** [comment]
@emmahodcroft do you specifically only want these notifications on new strains from GISAID or do you want them from Genbank, too?

**Comment by emmahodcroft** [comment]
Hmm. That is a good question. At the moment we don't have any way of integrating GenBank data easily so perhaps for now just GISAID, and I guess we could use a similar technique in future for GenBank if wanted?
